filter-by-commitish: true
commitish: develop
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '* $TITLE — #$NUMBER'
template: $CHANGES
exclude-labels:
  - 'dependencies'
  - 'chore'
  - 'docs'
  - 'infra'
autolabeler:
  - label: 'bug'
    branch:
      - '/(bug|hot)fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
