name: CI

on:
  push:
    branches:
      - develop
      - beta
      - prod
  pull_request:
    branches:
      - develop
      - beta
      - prod

env:
  FLUTTER_FORMAT_CMD: 'flutter format --set-exit-if-changed --line-length 150 .'

jobs:
  security:
    name: Check pipeline security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0
      - name: Ensure SHA pinned actions are used
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43 #1.0.4

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs:
      - security
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0
      - name: Read FVM config
        uses: kuhnroyal/flutter-fvm-config-action@c9c8517695e8de668802224f4fd867a99ff633b8 #0.0.2
      - name: Setup Flutter
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 #1.5.3
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter pub get
      - run: flutter analyze

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    needs:
      - security
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0
      - name: Read FVM config
        uses: kuhnroyal/flutter-fvm-config-action@c9c8517695e8de668802224f4fd867a99ff633b8 #0.0.2
      - name: Setup Flutter
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 #1.5.3
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - name: ${{ env.FLUTTER_FORMAT_CMD }}
        run: $FLUTTER_FORMAT_CMD

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs:
      - security
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0
      - name: Read FVM config
        uses: kuhnroyal/flutter-fvm-config-action@c9c8517695e8de668802224f4fd867a99ff633b8 #0.0.2
      - name: Setup Flutter
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 #1.5.3
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter pub get
      - run: flutter test
      - name: Upload unit test results
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 #2.2.4
        with:
          name: unit-test-results.json
          path: build/reports/test-results.json
      - name: Publish unit test results
        uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 #1.5.0
        if: success() || failure()
        with:
          name: Unit test results
          path: 'build/reports/test-results.json'
          reporter: dart-json

  android:
    name: Build Android
    runs-on: ubuntu-latest
    needs:
      - security
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0
      - name: Setup Java
        uses: actions/setup-java@8db439b6b47e5e12312bf036760bbaa6893481ac #2.3.1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Setup Android
        uses: android-actions/setup-android@a812d70a1a573b0fb349bbb220bb1259f8b9d7ca #2.0.7
      - name: Read FVM config
        uses: kuhnroyal/flutter-fvm-config-action@c9c8517695e8de668802224f4fd867a99ff633b8 #0.0.2
      - name: Setup Flutter
        uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 #1.5.3
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter build appbundle --release
