name: Draft Release

on:
  push:
    branches: [main, develop]

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0
      - run: echo ${GITHUB_REF}
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43 #1.0.4

  draft_release:
    name: Draft a release
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #2.4.0
      - name: Get pubspec.yaml version
        id: pubspec
        uses: CumulusDS/get-yaml-paths-action@991236f580834c47372ba6bda1648add8bd63c21 #0.1.0
        with:
          file: pubspec.yaml
          version: version
      - uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667 #5.0.0
        id: build-number
        with:
          script: |
            const query = `query($owner:String!, $name:String!, $ref:String!) {
              repository(owner:$owner, name:$name){
                ref(qualifiedName: $ref) {
                  target {
                    ... on Commit {
                      id
                      history(first: 0) {
                        totalCount
                      }
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              ref: context.ref,
            }
            const result = await github.graphql(query, variables)
            return result.repository.ref.target.history.totalCount
      - name: Draft the release
        id: release-drafter
        uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4 #5.15.0
        with:
          config-name: release-drafter-${GITHUB_REF}.yml
          disable-autolabeler: true
          name: ${{ steps.pubspec.outputs.version }}+${{ steps.build-number.outputs.result }}
          version: ${{ steps.pubspec.outputs.version }}+${{ steps.build-number.outputs.result }}
          tag: v${{ steps.pubspec.outputs.version }}+${{ steps.build-number.outputs.result }}
          prerelease: true
          commitish: ${GITHUB_REF}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
